# █▀▀ ▀▄▀ █▀▀ █▀▀
# ██▄ █░█ ██▄ █▄▄

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swaybg -m fill -i ~/pictures/wallpaper/1323469.png # Set wallpaper
exec-once = waybar
